[package]
name = "os-runtime"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
os-agents = { path = "../agents" }
os-automation = { path = "../automation" }
os-system = { path = "../system" }
os-tools = { path = "../tools" }
serde.workspace = true
serde_json.workspace = true
