use os_economy::{SurvivalThresholds,Treasury,TreasurySnapshot};use os_evolution::ChangeProposal;use os_execution::{AgentTask,ExecutionEngine,ExecutionResult,TaskStatus};use os_governance::DecisionClass;use os_revenue::{Opportunity,RevenueProject};use os_survival::SurvivalDecision;
#[derive(Clone,Debug)]pub struct Agent{pub id:String,pub role:String}
#[derive(Clone,Debug)]pub struct RuntimeSnapshot{pub agents:Vec<Agent>,pub treasury:TreasurySnapshot,pub survival:SurvivalDecision,pub opportunities:usize,pub changes:usize}
pub struct Runtime{pub agents:Vec<Agent>,pub treasury:Treasury,pub opportunities:Vec<RevenueProject>,pub changes:Vec<ChangeProposal>,pub execution:ExecutionEngine,thresholds:SurvivalThresholds,next_task:u64}
impl Runtime{pub fn new(b:i64)->Self{let roles=["Governor","Research","Business","Engineering","Content","Finance","Operations","QA","Security"];let agents=roles.iter().enumerate().map(|(i,r)|Agent{id:format!("agent-{:02}",i+1),role:(*r).into()}).collect();let mut treasury=Treasury::new(b);treasury.set_burn_rate(100);Self{agents,treasury,opportunities:vec![],changes:vec![],execution:ExecutionEngine::default(),thresholds:SurvivalThresholds{explore_days:30,operate_days:14,optimize_days:7,emergency_days:2},next_task:1}}
pub fn snapshot(&self)->RuntimeSnapshot{let t=self.treasury.snapshot(self.thresholds);RuntimeSnapshot{agents:self.agents.clone(),survival:os_survival::replan(t.mode),treasury:t,opportunities:self.opportunities.len(),changes:self.changes.len()}}
pub fn submit_task(&mut self,a:&str,c:DecisionClass,cost:i64)->ExecutionResult{let s=self.snapshot();let task=AgentTask{id:format!("task-{:06}",self.next_task),agent:a.into(),class:c,estimated_cost_cents:cost.max(0),status:TaskStatus::Queued};self.next_task+=1;self.execution.plan(&task,&self.treasury,s.treasury.mode,s.survival)}
pub fn register_opportunity(&mut self,o:Opportunity){self.opportunities.push(RevenueProject::new(o))}
pub fn register_change(&mut self,p:ChangeProposal){self.changes.push(p)}}
#[cfg(test)]mod tests{use super::*;#[test]fn boots(){assert_eq!(Runtime::new(100000).agents.len(),9)}#[test]fn readonly(){let mut r=Runtime::new(100000);assert_eq!(r.submit_task("agent-02",DecisionClass::ReadOnly,0).status,TaskStatus::Queued)}}